# Generated by Django 4.2.7 on 2024-01-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='coin_balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
