# Generated by Django 4.2.7 on 2024-01-16 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_useraccount_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='phone',
        ),
    ]
